#import = ["/home/strong/.config/alacritty/themes/themes/ubuntu.toml"]
import = [
    "~/.config/alacritty/themes/themes/iterm.toml"
]


[shell]
args = ['--login']
program = "/usr/bin/bash"

[cursor.style]
#style = "Beam"
shape = "Underline"
blinking = "Always"

[font]
size = 10.0

[font.normal]
family = "DejaVuSansM Nerd Font Mono"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 90
lines = 25

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

#### default
# [colors.normal]
# black = "#21222c"
# red = "#ff5555"
# green = "#50fa7b"
# yellow = "#f1fa8c"
# blue = "#bd93f9"
# magenta = "#ff79c6"
# cyan = "#8be9fd"
# white = "#f8f8f2"

# [colors.primary]
# background = "#282a36"
# foreground = "#f8f8f2"

# [colors.cursor]
# text = "CellBackground"
# cursor = "CellForeground"
######default
